name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas-profiling=3.3.0
  - pyyaml=5.3.1
  - pip=20.3.3
  - numpy=1.19.5
  - seaborn=0.11.1
  - pandas=1.2.3
  - ipykernel
  - jupyterlab = 3.0.12
  - pip:
      - wandb==0.13.2
      - protobuf==3.20.*

